# Generated by Django 3.2.8 on 2023-07-18 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='code',
            new_name='name',
        ),
    ]
